import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export const Route = createFileRoute("/mailbox")({
  head: () => ({
    meta: [
      { title: "Mailbox — SeatFlow" },
      { name: "description", content: "Ticket and waitlist emails generated by SeatFlow." },
      { property: "og:title", content: "Mailbox — SeatFlow" },
      { property: "og:description", content: "Ticket and waitlist emails generated by SeatFlow." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: MailboxPage,
});

function MailboxPage() {
  const { user, loading } = useAuth();
  const qc = useQueryClient();

  const { data: mails } = useQuery({
    queryKey: ["outbox", user?.id],
    enabled: !!user,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("email_outbox")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(50);
      if (error) throw error;
      return data;
    },
    refetchInterval: 10000,
  });

  async function flush() {
    const res = await fetch("/api/public/hooks/flush-emails", { method: "POST" });
    const json = (await res.json()) as { processed?: number; delivery?: string };
    toast.success(`Delivered ${json.processed ?? 0} email(s) (${json.delivery})`);
    void qc.invalidateQueries({ queryKey: ["outbox", user?.id] });
  }

  if (!loading && !user) {
    return (
      <main className="mx-auto max-w-md px-4 py-24 text-center">
        <h1 className="text-3xl">Sign in to read your mail</h1>
        <Button asChild className="mt-6">
          <Link to="/auth">Sign in</Link>
        </Button>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-3xl px-4 pb-24 pt-10">
      <div className="flex items-center justify-between">
        <h1 className="text-4xl">Mailbox</h1>
        <Button variant="secondary" size="sm" onClick={flush}>
          Deliver queued mail
        </Button>
      </div>
      <p className="mt-2 text-sm text-muted-foreground">
        Every ticket and waitlist offer SeatFlow generates lands here. Add a RESEND_API_KEY and the same
        messages go out as real email.
      </p>

      <div className="mt-6 space-y-4">
        {(mails ?? []).map((m) => (
          <article key={m.id} className="panel p-5">
            <div className="flex items-center justify-between gap-3">
              <h2 className="text-xl leading-tight">{m.subject}</h2>
              <Badge variant={m.status === "queued" ? "secondary" : "default"}>{m.status}</Badge>
            </div>
            <p className="text-xs text-muted-foreground">
              to {m.to_email} · {new Date(m.created_at).toLocaleString()}
            </p>
            <div
              className="mt-3 overflow-x-auto rounded-md bg-secondary/40 p-3 text-sm [&_a]:text-primary [&_a]:underline"
              dangerouslySetInnerHTML={{ __html: m.html }}
            />
          </article>
        ))}
        {(mails ?? []).length === 0 && <p className="text-muted-foreground">No mail yet.</p>}
      </div>
    </main>
  );
}
